### ISSUE TITLE
Unsub on a timer

### ISSUE THREAD

**Issue by dennismartensson** [nats-io/go-nats#169]
We could use a auto unsubscribe based on duration

So if there are no messages received on the subject for a duration of time it will unsubscribe but if there is a message the timer will be reset.

**Comment by derekcollison** [comment]
Like an inactivity timer?

**Comment by camros** [comment]
@dennismartensson if your goal is proxying web sockets and keeping sessions alive/managing state...

Then, you may find a method like this works for you:

1. create a _traditional http session like object_ to hold state on the web server side works for your web socket connection (e.g., for a new web socket client connection, create some state with a token, and your *nats client connection*).
2. The _session_ would be keyed, from a web socket client<->your proxy perspective, by a signed token passed back to your client something passed in your ws upgrade/etc.
2. Keep the _session_ alive for some configurable amount of time using timers or whatever makes sense (we'll say 10minutes).
3. After 10m/configurable amount of time has passed, garbage collect _sessions_ that have not had activity. Specifically: *close your nats connection* that for that _session_ (note: garbage collect may mean *unsubscribe clients from that connection*, depending upon your model of proxy client->nats connection, for example 1-1, M-1)
4. For each request on your web socket: create the _session_ if required or just update the current timer so you know it was used by the client. Check token, etc. and then use the _sessions_ *nats connection*

Same approach could apply to a long-poll client (e.g., a client doing a son request to your proxy).

Does this help?

**Comment by dennismartensson** [comment]
@derekcollison: Yes like an inactivity timer

@camros: Hi I have tried a number of solutions to make it scale well on the proxy side. My first naive approach was to create one connection for every websocket connection and then subscribe to the subjects this websocket connection needs. But as @ColinSullivan1 told me every subscribe is a go routine and then all the connections to NATS made it not scale in a good way. So the solution I have now is that the server creates one connection to NATS and then I use go channels to communicating between the server and the client routine and only create one subscription for every subject and have all the clients keep trace of the subjects this websocket have subscribed to and only forward message on subjects that that specific client have subscribed to. This looks to scale very well and then NATS server is preforming very very good under this solution.

The problem with this solution right now is that I will have to create some sort of subscription cleanup function so that the subscriptions don't increases forever . As I see it right now there is 3 solutions, 

1. Create a inactivity timer in my proxy for every subscription and have it unsubscribe if the timer is triggered and reset the timer for a subject every time I get a message. 

2. Create more of a master timer that will look at every client and see what subjects are not used by any client and unsubscribe them. This might be a good solution but are a bit afraid that it will slow down the server on an interval if there are many clients connected. Do you have any input on how I could write this in golang and make it fast?

3. Have the NATS client handle the unsubscribe. Having the NATS client handle it comes mostly from that fact that the client already have some functions similar to this.

**Comment by ColinSullivan1** [comment]
@dennismartensson I'm glad things are looking to scale well for you!

Yes, connections are tough to **massively** scale.  However subscriptions should scale better than connections.  How many concurrent websocket subscriptions do you need to handle?

In general I'd suggest starting simple and then optimizing as necessary.  I'd suggest trying #1 first, and if that works for you in a load test, great - you're done!  It's likely the simplest solution.  #2 could get complicated with concurrency issues, etc.  Another option to scale is to pool and reference count NATS subscriptions with an activity timer - somewhat of a hybrid between #1 and #2.  

We can certainly look into #3.

**Comment by dennismartensson** [comment]
So to let you know I did decide to go with a counter per subject that is +1 when a client joins and a -1 when a client disconnect and when there is 0 we do unsubscribe, This looks to be a very basic approach but takes care of what we needed.

**Comment by ColinSullivan1** [comment]
@dennismartensson  Great - a nice, simple solution!

**Comment by ColinSullivan1** [comment]
Closing this as part of housekeeping.  Since this issue was created, [conn.RequestWithContext](https://godoc.org/github.com/nats-io/go-nats#Conn.RequestWithContext) has been added which could be useful here.
