### ISSUE TITLE
nats should have a command line client

### ISSUE THREAD

**Issue by mikedanese** [nats-io/go-nats#200]
Similar to redis-cli. This allows bash scripting and easy interactive diagnostics.

**Comment by aricart** [comment]
Thanks for the feedback. Can you please elaborate a bit on the functionality that you are looking for and a sample session? Thanks!

**Comment by mikedanese** [comment]
Initially, a repl (like the telnet interface) that terminates tls/autn(n/z) would be very useful. I can think of a few features that I would like to see.
* Easily publish a single message
* Subscibe to a subject and exec a subcommand for each message with the message as an arg[1]
* Expose info from admin interface like perf and health of cluster

There are probably more but I need to play around with nats a bit more to buildup the list. Bash is very accessible and a command line tool is a great way to interactively explore a new api and prototype against it.

**Comment by wallyqs** [comment]
> Expose info from admin interface like perf and health of cluster
For this case you can check out nats-top and exposing monitoring port fron the nats server via `gnatsd -m` :) https://github.com/nats-io/nats-top/releases

**Comment by aricart** [comment]
> Easily publish a single message

the `nats-pub` example lets you easily publish a message:
`nats-pub <subject> <body>`

> Subscribe to a subject and exec a subcommand for each message with the message as an arg[1]

the `nats-sub` example lets you easily subscribe to a message:
`nats-sub <subject`

For the processing your pipeline could use something like `expect`.

**Comment by Swampy821** [comment]
I started a natscli for my own personal use with our micro-service project. You guys are welcome to use / contribute if you would like. https://github.com/Swampy821/natscli

**Comment by arulrajnet** [comment]
You have to install [ruby-nats](https://github.com/nats-io/ruby-nats) to use `nats-pub` and `nats-sub` command

For Ubuntu 16.04
```
sudo apt-get install ruby
sudo apt-get install ruby-dev
sudo gem install nats
```
Now run

```
nats-sub foo &
nats-pub foo 'Hello World!'
```

**Comment by aricart** [comment]
There are similar CLI for go-nats, java-nats, etc.
