### ISSUE TITLE
context.Context integration

### ISSUE THREAD

**Issue by mkabischev** [nats-io/go-nats#221]
Hi. 

In go 1.7 it was introduced context.Context interface. Are you going to support it in client?

**Comment by mcqueary** [comment]
Hi Mike (@mkabischev)! Sorry that no one has followed up on this until now. We have no immediate plan to introduce contexts in the client (that I know of). We'd be very interested in hearing your use case, though. How would you like to use contexts in the client? How often do you think would you use them? What would the benefit to you be in terms of implementation time/reduced complexity? Etc.

**Comment by mkorolyov** [comment]
Hi Larry (@mcqueary).
It became useful when you have for example micro service based architecture.
Single request from client needs to go through a bunch of internal services via some transport(e.g. great MQ NATS). 
In this case we need to wrap all internal requests with request deadline logic manually, while all necessary data is in instance of `context.Context`.
Actually it is not a big problem, but whole Golang ecosystem(e.g. database/sql, net/http etc) aimed to use `context.Context` for such things, so the client will not need to worry about it.

I could spend some time to add support of context.Context if motivation above is enough from your side.

**Comment by jack0** [comment]
It would be useful for us too to have built in context.Context support, right now we wrap each of the messages with certain fields in the context as well such as the request ID so we can do tracing of nats requests

**Comment by mkabischev** [comment]
Hi @mcqueary. As @mkorolyov and @jack0 mentioned `context.Context` is used for timeouts and cancelations. 

Also it would be great to have feature like [http tracing](https://blog.golang.org/http-tracing). Using it we`ll able to integrate nats client with `opentracing`.

**Comment by rusenask** [comment]
hello, any progress on this?

**Comment by mkorolyov** [comment]
@rusenask 
Hi, didn't get any comments(approve/decline) from @mcqueary about it. Don't want to spend time and this PR will not be merged :)

**Comment by rusenask** [comment]
from our case it would be useful to have context with cancellation on Request() function. In some cases we will need to cancel these requests in bulk and using context would be extremely helpful :)

**Comment by ColinSullivan1** [comment]
@rusenask , @mkorolyov Apologies for the delay here.  We do see merit to your suggestion, and do strive to keep NATS up to date with the go ecosystem.  I wanted to let you know that we're aware of this issue, we'll discuss the best way to move forward.  While this doesn't appear to be a roadblock for you, it does sound like a nice feature.  That being said, given the NATS tenet of simplicity and the need to get an API right the first time, API additions do not come lightly.

We do plan to provide guidance as to the best way to contribute here.  I'm thinking it could initially be by way of an API on top of NATS, to potentially be folded into the NATS client after some usage by the community, or possibly a direct contribution to the NATS API itself.  We'll let you know.

It is great to see interest and enthusiasm, and we really appreciate you using NATS!

**Comment by rusenask** [comment]
what about additional function? maybe something like 
```func (c *EncodedConn) RequestWithContext(ctx context.Context, subject string, v interface{}, vPtr interface{}, timeout time.Duration) error {```
Although it looked prettier in my head than what it looks like when written down.

Another option would be to have a different connection type, similar to plain conn and encoded one where Publish, Subscribe, Request functions all take context as well?

But I also agree with @ColinSullivan1 regarding that it's just a nice feature, not something critical. I guess at least for my case instead of using Request - I could write a custom wrapper for Publish and achieve the same thing. 

Thanks for making such a good product!

**Comment by ColinSullivan1** [comment]
@rusenask , Thanks, the team and I always appreciate hearing that!

IMO, `RequestWithContext` sounds like a great place to start, although I'd begin a layer lower with a the standard conn `RequestWithContext` API, then wrap an encoded conn `RequestWithContext` API around it.

Would you think the timeout would work better as part of the context (`context.WithTimeout(...)`) versus being passed as a parameter?  The API could return a nil msg and new error, `"nats:  context error"`, for the case the context times out or has been cancelled; the caller would use `Context.Err()` to discover exactly why.  For other cases, the connection could be checked for connection related errors resulting in a nil msg.  

Here is some very quick and rough code to convey my thinking (_caveat:  this is just for API discussion - it may have bugs and there is likely a better way_) :
```
func (nc *Conn) RequestWithContext(ctx context.Context, subj string, data []byte) (*Msg, error) {
	inbox := NewInbox()
	ch := make(chan *Msg, RequestChanLen)
	recvCh := make(chan *Msg, 1)
	var recvMsg *Msg

	s, err := nc.subscribe(inbox, _EMPTY_, func(msg *Msg) {
		recvCh <- msg
	}, ch)

	if err != nil {
		return nil, err
	}
	s.AutoUnsubscribe(1)
	defer s.Unsubscribe()

	err = nc.PublishRequest(subj, inbox, data)
	if err != nil {
		return nil, err
	}

	select {
	case <-ctx.Done():
		if ctx.Err() != nil {
			err = errors.New("nats: context error")
		}
	case recvMsg = <-recvCh:
		break
	}
	return recvMsg, err
}
```

Calling code:

```
	ctx, _ := context.WithTimeout(context.Background(), 5*time.Second)
	msg, err = nc.RequestWithContext(ctx, "foo", []byte("help"))	
        if err != nil {
		fmt.Printf("Received an error on Request: %s", err)
		fmt.Printf("Context Error = %s", ctx.Err())
	}

```
WDYT?

**Comment by rusenask** [comment]
looks great, I would definitely prefer `ctx, cancel := context.WithTimeout(context.Background(), time.Duration(5*time.Second))` and then ctx passed as a parameter since in some cases users might call `cancel()` even before the timeout.

**Comment by ColinSullivan1** [comment]
@rusenask , Thanks.  I think cancel will still work with the proposed API (although I did ignore it in the snippet above - sorry).

After some discussion with the team, the best approach we see involves three new APIs:
* `func (c *EncodedConn) RequestWithContext(ctx context.Context, subject string, v interface{}, vPtr interface{}) error`
 * `func (nc *Conn) RequestWithContext(ctx context.Context, subj string, data []byte) (*Msg, error) `
 * `func (s *Subscription) NextMsgWithContext(ctx context.Context) (*Msg, error)`

These APIs would be layered where the `EncodedConn.RequestWithContext` would call `Conn.RequestWithContext` which in turn calls `Subscription.NextMessageWithContext`.  The next message API will select on the context and internal message channel, update stats, etc.  While this is a bit more intrusive, this approach facilitates optimization of the client as to provide the best performance possible.  As a bonus, there would be more API options available for NATS users.

I'd love to hear any comments, thoughts, etc, on the proposed APIs...

**Comment by rusenask** [comment]
Looks great :)

**Comment by joeblew99** [comment]
This would help me alot. I have various transports on top of Nats and they all use the context to enable cancellations.
So if NATS also supports it the cancellation will propose.
Main use case for me is IOT and mobile where connections are often killed in flight 

Really amazing product btw - solved many tough sticky issues for me
