### ISSUE TITLE
can i publish and subscrible from multiple go routine with one Conn?

### ISSUE THREAD

**Issue by dbskccc** [nats-io/go-nats#241]
can i publish and subscrible from multiple go routine with one Conn?
or must be protected by mutex?

**Comment by mcqueary** [comment]
Hi and thanks for your interest in NATS. The `Conn` is protected by its own internal mutex, so yes, it is thread-safe and you can use the public API calls safely on the same `Conn` from different goroutines.

**Comment by dbskccc** [comment]
thanks for the clarification! the info should  add to the README.md.
