### ISSUE TITLE
too slow, whats the problem?

### ISSUE THREAD

**Issue by monopollly** [nats-io/go-nats#242]
I made a simple empty test on my 15 retina mac, (8gb) but is so slow...
could you explain about it?
Thanks!

1 server
1 client
1 thread

```go
for i := 0; i < 200000; i++ {
       nc.Request("test", []byte("ok?"), Time1s)
}
```
1 subscriber
```go
nc.QueueSubscribe("test", group, testsimpleempty)
```

subscribe function
```go
func testsimpleempty(m *nats.Msg){
    nc.Publish(m.Reply, []byte("OK"))
}
```

and here is...
1887-2600 request per seconds:)
https://gyazo.com/e72b8f976bd15241ba8025787437fd31

how to get 30k, 100k, 1m?

**Comment by monopollly** [comment]
server run via docker, maybe so big overhead?

**Comment by kozlovic** [comment]
`Request()` is a request reply, which means a round trip with the server. The number seem low, but still, a request/reply is a synchronous operation and not going to perform as well as simple publish or subscribe.

A single stream of request/reply will be bounded. To improve performance you would need to increase the number of processes/go routines/threads/etc. doing request/reply in parallel.

**Comment by monopollly** [comment]
thank you!
