### ISSUE TITLE
Q: publish to all servers in a cluster?

### ISSUE THREAD

**Issue by glycerine** [nats-io/go-nats#250]
Is it possible to have a publishing client send a copy of each published message to each server in a nats high-available server cluster?

Note that I'm trying to understand how to achieve high-availability, to necessarily recommending any  change to nats.  If this question doesn't make sense, because a server cluster already guarantees that all servers see all messages, just let me know.

**Comment by derekcollison** [comment]
As much as NATS makes guarantees, it will make sure to attempt to send a message received from a publishing client to all servers in a connected cluster.
