### ISSUE TITLE
GOB decoding an interface

### ISSUE THREAD

**Issue by KEANO3** [nats-io/go-nats#254]
I'm trying to receive an interface through NATS like the guy in issue #245
I know that JSON can't help us here (directly) but GOB can.

After taking the example from #245 and upgrading it with GOB it looks like this:

    type Event interface {
        GetName() string
    }

    type event struct {
        Name string
    }

    func (e event) GetName() string {
        return e.Name
    }

    func main() {
        gob.Register(event{})
        myEvent := event{"test"}

        var network bytes.Buffer
        var message Event
        enc := gob.NewEncoder(&network)
        dec := gob.NewDecoder(&network)

        message = myEvent
        enc.Encode(&message)

        var result Event
        dec.Decode(&result)
        fmt.Println(result.GetName())

        nc, _ := nats.Connect(nats.DefaultURL)
        ec, _ := nats.NewEncodedConn(nc, nats.GOB_ENCODER)
        defer ec.Close()

        in := make(chan Event)
        ec.BindRecvChan("events", in)

        out := make(chan interface{}, 10)
        ec.BindSendChan("events", out)

        out <- &message

        fmt.Println(<-in)
    }

As you see using GOB directly is successful, but trying to receive this via NATS fails.

Is there any chance to get this to work with NATS?

**Comment by kozlovic** [comment]
As in the previous issue, if you use the async error handler (`nc.SetErrorHandler()`), you would see the following message:
```
nats: Got an error trying to unmarshal: gob: local interface type *nats.Event can only be decoded from remote interface type; received concrete type event = struct { Name string; }
```
I see two ways of fixing this. Either you use the concrete type for the receiving channel:
```
in := make(chan event)
```
Or, you need to send an `Event`. For instance, you could have the following function:
```
func newEvent(name string) Event {
    return event{name}
}
```
Then, send this way:
```
message := newEvent("test")
out <- &message
```
That works for me. Let me know.

**Comment by KEANO3** [comment]
The concrete type doesn't do the trick in my case as I use different implementations.

    type Name interface {
        Name() string
    }

    type Organisation struct {
        name  string 
        taxID string
    }
    func (o Organisation) Name() string {
        return o.name
    }

    type Person struct {
        title     string
        firstName string
        lastName  string
    }
    func (p Person) Name() string {
        return p.title + p.firstName + p.lastName
    }

I'm currently avoiding the problem with a concrete type wrapper.
But imho the interface solution would be a more idiomatic approach

**Comment by kozlovic** [comment]
@KEANO3 Again, the error callback would tell you that `Person` (or `Organization`) does not have exported fields, so that can't work. 
If you fix that, add `gob.Register` both `Organization` and `Person`, and two `newOrganization` and `newPerson` functions that return the interface `Name` and send that, it will work ok.
