### ISSUE TITLE
Intermittent TLS connection errors on ARM.

### ISSUE THREAD

**Issue by shanna** [nats-io/go-nats#269]
I haven't done a lot of investigation yet but I'm getting a TLS connection error on go1.8.linux-armv6l from go-nats on a bunch of RPI3's:  `server connection error tls: received record with version 4552 when expecting version 303`

I have `nats.MaxReconnects(-1),` but I'm not seeing reconnect attempts after above error either. I haven't been able to replicate on amd64. I get the error roughly 20% of the time as the binary is executed so I'm wondering if there may be a race condition somewhere.

**Comment by kozlovic** [comment]
@shanna I wonder if this would not be caused by https://github.com/nats-io/gnatsd/issues/432.
If that's the case, you may want to increase the server's TLS timeout through configuration to see if it reduces the error occurrences.

**Comment by shanna** [comment]
The server isn't under heavy load, it's got almost no traffic (~1 message a minute tops) and the clients aren't all trying to connect at the same time. The clients are working quite hard though. They are doing a load of HTTPS traffic while nats is trying to establish the first connection.

**Comment by wallyqs** [comment]
@shanna just curious, but around how long does it take before attempting to connect until getting `server connection error tls`?

**Comment by kozlovic** [comment]
@shanna Sorry. What I meant is that this is probably due to heavy load, but instead that the TLS handshake times out and the server sends an authentication timeout message while the TLS connection is not fully established, causing the error you are reporting.
I would still recommend that you increase the TLS and authentication timeout to see if it helps.

**Comment by kozlovic** [comment]
@shanna Note that the server defaults the TLS timeout to a mere 0.5 seconds if you did not configure it.

**Comment by shanna** [comment]
@kozlovic ah ok, yeah that could be an issue over wifi. I'll adjust natsd tomorrow and report back.

**Comment by shanna** [comment]
Increasing the TLS timeout has fixed the TLS connection issue it seems.

The lack of reconnect attempts that followed the TLS error was because that initial connection is required in go-nats and I'd missed that. It makes sense in a lot of cases I guess since it validates the credentials. I've refactored the code on my end since a nats connection is only desired not required.

Thanks for all your help.
