### ISSUE TITLE
golang concurrent queueing workers with multiple subscribers

### ISSUE THREAD

**Issue by rohitjankar** [nats-io/go-nats#271]
I wanted to creating golang subscriber client,

My requirement is as follows,
    1. It should work in infinite loop to listen input events.
    2. Concurrent execution with multiple workers.
    3. Workers should work on its own queue.

Any help appreciated.

**Comment by mcqueary** [comment]
Hi Rohit (@rohitjankar), your problem sounds like a great candidate for a [Queue Group](https://github.com/nats-io/go-nats#queue-groups).
