### ISSUE TITLE
Encoder.Decode() doesn't invoked for simple subscription.

### ISSUE THREAD

**Issue by mkorolyov** [nats-io/go-nats#278]
Hi, 

why current implementation of client doesn't invoke Encoder.Decode() for simple subscription with handler type `handler := func(m *Msg)` ?
i am speaking about `https://github.com/nats-io/go-nats/blob/master/enc.go#L188`

Case that i met is when i need to register customer Encoder i expect it to be called.

Thanks

**Comment by derekcollison** [comment]
Can you provide us more ifa complete program that shows the behavior? Is the encoder custom? Has it been regsitered?

**Comment by mkorolyov** [comment]
@derekcollison Hi,

yes, it is custom encoder that implements Encoder interface. It has been registered, but it is not invoked bc of the logic i pointed above. actually that logic isn't connected to Encoder implementation. it just doesn't invoke it on described condition(if subscribed handler declared as `func(msg *Msg)`

**Comment by derekcollison** [comment]
If you are willing to send us a complete example that would help us in looking at the issue.

**Comment by mkorolyov** [comment]
@derekcollison have you looked at the code that i posted? it is not an issue, it is current documented solution in `enc.go`. I am asking for motivation for it and if it will be possible change it, or not if motivation will be sufficient.

**Comment by kozlovic** [comment]
If I understand correctly, the code you are pointing to is the case where the user provided a handler of the form `func (m *nats.Msg)`, in which case, why would the library decode since the user specifies that the incoming data is expected to be a raw, default, `nats.Msg`?

**Comment by mkorolyov** [comment]
@kozlovic yeah, it could be raw nats.Msg with Data in it encoded in custom way(gzip, base64, whatever).

**Comment by kozlovic** [comment]
If you use a custom encoder, you first need to register it using `RegisterEncoder()`. Then, create an `EncodedConn` calling `NewEncodedConn()` with the encoded type string you used to register your encoder.

From that connection, when you call `Subscribe()`, you would then pass an `Handler` that the library will invoke after calling `Enc.Decode()`, and will pass the decoded object to the `Handler`.

The handler's signature should not use `nats.Msg` otherwise you are signaling it to pass objects untouched, as described in `enc.go`:
```
// Handlers are expected to have one of four signatures.
//
//	type person struct {
//		Name string `json:"name,omitempty"`
//		Age  uint   `json:"age,omitempty"`
//	}
//
//	handler := func(m *Msg)
//	handler := func(p *person)
//	handler := func(subject string, o *obj)
//	handler := func(subject, reply string, o *obj)
//
// These forms allow a callback to request a raw Msg ptr, where the processing
// of the message from the wire is untouched. Process a JSON representation
// and demarshal it into the given struct, e.g. person.
```
Notice the sentence that says that `nats.Msg` will cause the processing of the message from the wire to be direct.

As @derekcollison mentioned, if you are willing/allowed to send some code, maybe we could help better. Thanks!

**Comment by kozlovic** [comment]
For instance, here is a really simple example of creating my own encoder/decoder that simply prepend the message payload with `@@IK:` when encoding, and strip it off when decoding. Notice the use of a custom object. As you saw, using `nats.Msg` would cause skipping the decoder:
```
type MyEncoder struct{}

type MyMsg struct {
	Data []byte
}

func (me *MyEncoder) Encode(subject string, obj interface{}) ([]byte, error) {
	m := obj.(*MyMsg)
	result := fmt.Sprintf("@@IK:%s", string(m.Data))
	return []byte(result), nil
}

func (me *MyEncoder) Decode(subject string, data []byte, vPtr interface{}) error {
	origin := string(data)
	payload := origin[5:]
	m := vPtr.(*MyMsg)
	m.Data = []byte(payload)
	return nil
}

func TestIvan(t *testing.T) {
	RegisterEncoder("myEncoder", &MyEncoder{})
	errCb := func(_ *Conn, _ *Subscription, err error) {
		t.Fatalf("Got error: %v", err)
	}
	nc, _ := Connect(DefaultURL, ErrorHandler(errCb))
	defer nc.Close()
	ec, err := NewEncodedConn(nc, "myEncoder")
	if err != nil {
		t.Fatalf("Error creating encoded connection: %v", err)
	}
	wg := sync.WaitGroup{}
	wg.Add(1)
	if _, err := ec.Subscribe("foo", func(m *MyMsg) {
		fmt.Printf("Got message: %v\n", string(m.Data))
		wg.Done()
	}); err != nil {
		t.Fatalf("Error on subscribe: %v", err)
	}
	if err := ec.Publish("foo", &MyMsg{Data: []byte("hello")}); err != nil {
		t.Fatalf("Error on publish: %v", err)
	}
	wg.Wait()
}
```

**Comment by mkorolyov** [comment]
@kozlovic So, if i will define a copy of nats.Msg(a struct with same fields) and subscribe endpoint that expect it in params, Encoder.Decode() will be invoked?

My setup already in production thats why i can't change data representation, bc now it is nats.Msg.

Go it, thanks guys a lot!
