### ISSUE TITLE
Question on request/reply - one-to-many

### ISSUE THREAD

**Issue by davisford** [nats-io/go-nats#287]
Hi, I just have a quick question about nats behavior with request-reply.

The [docs here](http://nats.io/documentation/concepts/nats-req-rep/) describe the following:

`NATS supports two flavors of request reply messaging: point-to-point or one-to-many. Point-to-point involves the fastest or first to respond. In a one-to-many exchange, you set a limit on the number of responses the requestor may receive.`

I'm curious how this would work.  It seems with the API (the way I understand it) the request sets a timer, and the first responder wins.  Is there a way to gather the results of multiple responders within the timeout duration and return the aggregate?

**Comment by derekcollison** [comment]
The server can be configured to only receive a certain number of responses on any subscription. Once the limit is reached the subscription from the server side will be invalid.

Any aggregation would need to be done in the client since NATS does not have an understanding of message contents.

**Comment by davisford** [comment]
Hi @derekcollison thanks for the quick reply.  I get the part of about the aggregation and not peeking into message content, but can you point me to the part that describes how to set the server up for receiving a finite number of responses on a particular subscription?  Is this configurable by the client at all when they set up the subscription?

**Comment by kozlovic** [comment]
@davisford This is all done in the client. To summarize, if you use `Request()`, the API is internally creating a subscription on an inbox and auto-unsubscribing after 1 reply is received. The API then returns you the single reply or a timeout if none is received.
If you want many replies, you need to do this steps on your own, that is, create a subscription (on Inbox or anything you like), call `sub.AutoUnsubscribe(max int)` with the max number of replies you want, then send the request using the ` (nc *Conn) PublishRequest(subj, reply string, data []byte)` API.
Let me know if you have more questions.
