### ISSUE TITLE
Question on Reconnect / Failure logic

### ISSUE THREAD

**Issue by davisford** [nats-io/go-nats#288]
I understand how the reconnect logic works (I think), and I've tested it myself with a local cluster -- taking down gnatsd instances intermittently with reconnection logic.

What I'm wondering is if I need to re-initialize any subscriptions I've setup after the reconnect handler is triggered, or if those subscriptions will continue to operate once the connection is re-established?  I'm not so concerned about lost messages, and I understand there is a finite buffer where it stores outbound messages and will flush them after a reconnect.

I'd just like to know if in this section:

```go
  nats.ReconnectHandler(func (nc *nats.Conn) {
      // do i need to re-initialize subscriptions in here?
  })
```

**Comment by kozlovic** [comment]
@davisford No, you don't need to recreate the subscriptions if the client library was able to automatically reconnect. Existing subscriptions will be resent to the server after reconnection. If your application creates subscriptions while being disconnected, the protocols go into the reconnect buffer, which, as you say, is of a finite size (and can be configured with ReconnectBufferSize). At any rate, as long as the protocol is in the buffer, it will be flushed after the library reconnects.

**Comment by davisford** [comment]
Fantastic news.  Thank you for the clarification.
