### ISSUE TITLE
Is thread-safe in "Conn.Subscribe" callback?

### ISSUE THREAD

**Issue by zombiecong** [nats-io/go-nats#291]
Is thread-safe in "Conn.Subscribe" callback ? should I add mutex protecting the global variable in the callback?

**Comment by derekcollison** [comment]
Subscriptions, asynchronous ones, run in their own Go routine. If you are only accessing via the callback you should be fine, but a RWMutex, Mutex or Atomic may be required. Running tests with --race will giv you good information as well.

**Comment by zombiecong** [comment]
thx
