### ISSUE TITLE
go get broken?

### ISSUE THREAD

**Issue by Corni** [nats-io/go-nats#298]
Hi,

when executing
go get github.com/nats-io/go-nats

I get the error
gopath/src/github.com/nats-io/go-nats/nats.go:25:2: no buildable Go source files in gopath/src/github.com/nats-io/go-nats/util

Did I do something wrong?

root@jessie-test:/home/vagrant# go version
go version go1.3.3 linux/amd64

**Comment by tylertreat** [comment]
@Corni Are you able to update your version of Go? 1.3.3 is quite old. I'm not able to reproduce with the following version:

```
go version
go version go1.8.1 darwin/amd64
```

**Comment by Corni** [comment]
Thanks - this problem occured first on a travis-provided VM with go version 1.4.1, using 1.7.5 and 1.8 go get works for me as well.
I will look how to get an updated go version on the travis machine, thanks!
