### ISSUE TITLE
Wildcard Publisher

### ISSUE THREAD

**Issue by wllenyj** [nats-io/go-nats#302]
``` Go
// Server A
nc.Subscribe("task.hostnameA", func(m *nats.Msg) {
    fmt.Printf("Received a message: %s\n", string(m.Data))
})

// Server B
nc.Subscribe("task.hostnameB", func(m *nats.Msg) {
    fmt.Printf("Received a message: %s\n", string(m.Data))
})

// I want to publish a message to all of the ServerA and the ServerB
nc.Publish("task.*", []byte("Hello Cluster"))

// or publish to ServerA
nc.Publish("task.hostnameA", []byte("Hello ServerA"))
```

**Comment by tylertreat** [comment]
Wildcards are a subscribe-side mechanism, not publish-side. They allow a subscriber to match on published messages. That is to say, publishing on `task.*` simply publishes to a literal topic called `task.*` and nothing else.

To do what you want, you would probably need two subscriptions: one for the cluster and one for the individual host. Note that's essentially what you're already doing here by publishing on `task.*` and then on `task.hostnameA`, you just need to reverse the responsibilities—subscribers determine message matching, not publishers.

**Comment by wllenyj** [comment]
Thanks for you answers.
I just want to do this more easier.I think this feature is very useful.

**Comment by tylertreat** [comment]
It is useful, but publishing on a wildcard is not supported, only subscribing on one.

**Comment by kozlovic** [comment]
As @tylertreat said, you simply need to have 2 subscriptions `nc.Subscribe("task.all", ...)` and `nc.Subscribe("task.hostnameA", ...)` on server A (same for server B) and then publish on either `task.all` for all servers or `task.hostnameA` for server A.
