### ISSUE TITLE
Messages are published but do not reach

### ISSUE THREAD

**Issue by gitchander** [nats-io/go-nats#303]
If I publish message for absend subscriber there is no error. I close Publisher.
After run subscriber nothing receiveing.
Comment please.

**Comment by kozlovic** [comment]
NATS does not have persistence. So this is normal. If you want persistence, you can have a look at something like NATS Streaming: [server](https://github.com/nats-io/nats-streaming-server) and [go client](https://github.com/nats-io/go-nats-streaming)

**Comment by gitchander** [comment]
Thanks!
I'll take a look
