### ISSUE TITLE
Connect callback

### ISSUE THREAD

**Issue by ripienaar** [nats-io/go-nats#306]
We have various callbacks for error conditions but none for happy path.

I'd love to log to my clients which server they are connected to whenever a connection is established and cannot see a way to do that.

**Comment by mdevan** [comment]
Not a contributor, just curious! My understanding is that even if there were callbacks, the server wouldn't be able to send unsolicited messages to the client -- the client does not have a "default inbox" to receive the messages.

**Comment by kozlovic** [comment]
Although lots of APIs are asynchronous, `Connect()` is synchronous in Go client. So if the `Connect()` calls returns without error, then you can get the URL you are connected to with `ConnectedUrl()`. For reconnect, you can setup a (reconnected) callback.

**Comment by ripienaar** [comment]
Thanks. I had not realised it's synchronous - I should probably do that in a Go routine then because I would not want to wait forever should it not be able to connect

Thanks. Happy to use that feature. Will close this.

**Comment by kozlovic** [comment]
Actually, you will not wait for ever, since as of now, the client will try to connect to each of the given URLs, and at most wait for `Options.Timeout` on each connect. On non Windows system, a connect to a non running server will fail immediately, so you are not likely to wait at all if no server in the pool is running.

**Comment by ripienaar** [comment]
And if they are all down? Start from the top? Down might mean unreachabke so each will wait max timeout or quite a while

**Comment by kozlovic** [comment]
Again, on non Windows systems, the low level connect() will usually fail right away. But if you chose to run `Connect()` in a go routine, then you would obviously need to synchronize your other calls to publish/subscribe so that they are not done before the connect succeeds.

**Comment by ripienaar** [comment]
I will test thanks. TCP Timeout is unavoidable you can't fail immediately for machines that do not answer a SYN with anything.

**Comment by ripienaar** [comment]
this will take timeout * nservers to return, its not possible to be immediate in the face of no responses.  It will cycle through the servers once and then not do any retry logic once failed.

During initial setup errors are not logged or callbacks called so its impossible to give users feedback on why it's not connecting.

For instance to figure out why it was failing immediately for me when I thought it impossible I had to hack the library to add some print's to find:  `dial tcp: address 192.168.88.150: missing port in address`, there was no way to extract this from the library since the error `Connect` made was `nats: no servers available for connection` which is not useful

I'm inclined to re-open this again or make a new issue about general visibility of actions in the library.  Library users must be able to give their users insight into why it's apparently not connecting or what the issues was.

What do you think @kozlovic ?
