### ISSUE TITLE
BUG: a Client can't authorize by a token

### ISSUE THREAD

**Issue by sarbash** [nats-io/go-nats#316]
I've tried a client authorization by token and always get the error:

```shell
sergey@debian:~/go/src/gitlab.com/sarbash/tms-notifyd$ go run main.go 
2017/08/19 21:52:45 nats: authorization violation
exit status 1
```

The code is as follows:

```go
const (
	natsServer = `nats://xxxxxx.yyyyyyyy.ru:4222`
	orderSubj  = `orders.Update`
	natsToken  = "$xx$xx$XXxXXXXXXXxXxxxxXXXxXXXxXXxxXxXXxXXXXXXxXXxX/XxxxXXxX"
)

func main() {
	natsConnection, err := nats.Connect(natsServer, nats.Token(natsToken))
	if err != nil {
		log.Fatalln(err)
	}
	log.Println("Connected to NATS")

	// Subscribe to subject
	cb := msgHandler
	log.Printf("Subscribing to subject '%s'\n", orderSubj)
	natsConnection.Subscribe(orderSubj, cb)

	// Keep the connection alive
	runtime.Goexit()
}
```

**Comment by sarbash** [comment]
In addition to the above:

Inter-servers connection by a token works just fine.

**Comment by sarbash** [comment]
Sorry, it seems that I can't authorize anyhow. I should investigate it deeper.

**Comment by tylertreat** [comment]
Can you post your server config?

**Comment by sarbash** [comment]
My further inquiry of this issue revealed that a client may not authorize by token or bcrypt password.
I've tried all possible combinations and user/passwd connect only was successful.
I've used util/mkpasswd.go utility to generate token.

**Comment by sarbash** [comment]
My config:

```nats
# Client port of 4222 on all interfaces
port: 4222

# HTTP monitoring port
monitor_port: 8222

# Authorization for client connections
authorization {
  token: $xx$xx$xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/xxxxxxxx
  timeout:  1
}

# This is for clustering multiple servers together.
cluster {

  # Route connections to be received on any interface on port 6222
  port: 6222

  # Routes are protected, so need to use them with --routes flag
  # e.g. --routes=nats-route://ruser:T0pS3cr3t@otherdockerhost:6222
  authorization {
    token: $xx$xx$xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/xxxxxxxx
    timeout:  0.75
  }

  # Routes are actively solicited and connected to from this server.
  # This Docker image has none by default, but you can pass a
  # flag to the gnatsd docker image to create one to an existing server.
  routes = [$NATS_SEED_HOST]
}
```

**Comment by tylertreat** [comment]
It looks like you're passing the bcrypt hash as the token. You should use the password. I've verified the same config works on my machine.

**Comment by sarbash** [comment]
Thank you for the clarification.
But, what's about this: [Securing NATS](https://github.com/nats-io/gnatsd#securing-nats)?
And this:
>For single-user authentication, you can start the NATS server with authentication enabled by passing in the required credentials on the command line, or by passing in a token.

>Or, if you chose to use a token:
>
>authorization {
>  # You can generate the token using /util/mkpassword.go
>  token:   $2a$11$pBwUBpza8vdJ7tWZcP5GRO13qRgh4dwNn8g67k5i/41yIKBp.sHke
>  timeout: 1
>}

**Comment by tylertreat** [comment]
Yes, the bcrypt hash goes in the `token` config, but the associated password is used to connect. Can you verify that works?

**Comment by sarbash** [comment]
I'v e tested with both pass+token in config:
```
sergey@debian:~/go/src/gitlab.com/TransportSystem/backend/mq_service$ docker logs nats 
2017-08-19T22:38:10.242526206Z control: serving at /containerpilot.socket
2017-08-19T22:38:10.244667039Z Cannot have a user/pass and token
2017-08-19T22:38:10.244949432Z nats exited with error: exit status 1
2017-08-19T22:38:15.519750727Z killing processes for job "nats"
```
Now, I leave the token in config and wil try to authenticate using the password.

**Comment by sarbash** [comment]
This:
```
# Authorization for client connections
authorization {
  token:    $xx$xx$xxxxxxxxxxxxx.x.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  timeout:  1
}
```
simply doesn't work.

Wrong doc?

Only user/password authentication for clients is working.

**Comment by tylertreat** [comment]
The following configuration works for me with nats-server version 1.0.0:

```
$ go run mkpasswd.go
pass: RPsTaOgu054hJSAhXa2rhd
bcrypt hash: $2a$11$v0wp3xFBbdhRoMTg4PMx6ON2qnm4gImadS8Of3cneUAbUZbXsScC.
```

```
port: 4222

authorization {
  token: $2a$11$v0wp3xFBbdhRoMTg4PMx6ON2qnm4gImadS8Of3cneUAbUZbXsScC.
  timeout:  1
}
```

```go
package main

import (
        "fmt"
        "github.com/nats-io/go-nats"
)

func main() {
        conn, err := nats.Connect(nats.DefaultURL, nats.Token("RPsTaOgu054hJSAhXa2rhd"))
        if err != nil {
                panic(err)
        }
        defer conn.Close()
        fmt.Println("connected")
}
```

```
$ go run main.go
connected
```

**Comment by sarbash** [comment]
I'm gonna crazy...
I set a token in server's config.
Then I set an associated password with that token in a client.
Then I used the password as 'Token' param in a client.
Then It Works!
But how and why? Shouldn't I use the same token in a client and in a server?
Where in the docs is it described?
This completely confused me.

**Comment by sarbash** [comment]
Using a generated "pass" as a 'token' in a client is confusing a bit.
Now I get it.
@tylertreat  Thank you very much for the help and the explanation.

**Comment by tylertreat** [comment]
Glad you got it working! Feel free to make a PR to any documentation you find unclear. Closing this issue for now.

**Comment by lemonkey** [comment]
The official documentation still needs to be updated..
