### ISSUE TITLE
publish with "\n"  causing connection close

### ISSUE THREAD

**Issue by zombiecong** [nats-io/go-nats#317]
client code :
```
err := nc.Publish("\n","xxx")
```

Server log ：
```
[43695] 2017/08/29 15:01:45.149740 [ERR] ::1:54586 - cid:4 - Error reading from client: processPub Parse Error: 
```

No error is returned in client , and the server error make the  connection of  the client closed.

**Comment by tylertreat** [comment]
`\n` is an invalid subject. When the server receives an invalid protocol message, it disconnects the client.

**Comment by tylertreat** [comment]
Closing this for now. Feel free to reopen if you have further questions.
