### ISSUE TITLE
message receiving

### ISSUE THREAD

**Issue by gitchander** [nats-io/go-nats#318]
When the publisher send (Publish) a message (when subscriber is not connected) function Publish return nil. The message is lost, but we do not know that it was not received.
How can I make sure that the "Subscriber" received the message?

**Comment by tylertreat** [comment]
You are correct in that NATS is at-most-once delivery, so there are no delivery guarantees. What you typically do is layer on the guarantees your application needs. For example, if you need to guarantee delivery of a message, you could have the receiver send an acknowledgement back to the sender indicating they received and processed it. There is a convenience function called [Request](https://godoc.org/github.com/nats-io/go-nats#Conn.Request) which publishes a message and synchronously waits for a response.

Alternatively, you could look at [NATS Streaming](https://github.com/nats-io/nats-streaming-server) which provides at-least-once delivery of message by providing a persistence layer on top of NATS.

**Comment by tylertreat** [comment]
Closing this for now. Feel free to reopen if you have further questions.
