### ISSUE TITLE
How to get cached size of specify queue name in nats server?

### ISSUE THREAD

**Issue by rafw** [nats-io/go-nats#328]
I want to get message size which didn't be consumed yet. Thanks.

**Comment by tylertreat** [comment]
The NATS server ([gnatsd](https://github.com/nats-io/gnatsd)) does not store messages, so if consumers are offline when messages are published, they will not be received. For at-least-once delivery, see [NATS Streaming](https://github.com/nats-io/nats-streaming-server).

**Comment by rafw** [comment]
I am confused.

Now the question is:

If consumers are all using nc.QueueSubscribeSync() to consume message. Where does the published messages cached? Producer process or nats-server?

**Comment by nussjustin** [comment]
It depends on your client library, how you configure it and how you subscribe to a topic.

NATS at its core is a fire-and-forget style system. Neither the NATS server (gnatsd) nor the publishers do any buffering of messages.

If you publish a message but there are no subscribers for the topic the message will be dropped. If there are subscribers for the topic the server will try to deliver the message to them (all non-queue subscribers, and one of each queue) and disconnect all subscribers that time out (the timeout is configurable and defaults to 2 seconds in gnatsd).

The client libraries may buffer received messages, but the buffer will generally be of fixed (but configurable) size and drop messages when the buffer is full. 

See the documentation on [slow consumers](http://nats.io/documentation/server/gnatsd-slow-consumers/) for more details on how the client libraries and gnatsd handle this.

There is an [open proposal](https://github.com/nats-io/gnatsd/pull/571) by @tylertreat to add a special topic (_SYS.dlq.*) which will receive messages for which no subscribers exists, but this doesn't handle the case where clients time out or are buffering messages.

If you want real message persistence and redelivery you can use [NATS Streaming](http://nats.io/documentation/streaming/nats-streaming-intro/), which builds on top of NATS and adds many extra features and guarantees.
