### ISSUE TITLE
question about customize dialer

### ISSUE THREAD

**Issue by joyhope** [nats-io/go-nats#329]
Dialer option

func Dialer(dialer *net.Dialer) Option {
	return func(o *Options) error {
		o.Dialer = dialer
		return nil
	}
}

It required net.Dialer structure.  It is not an interface.  I like to provide the customized dialer, eg. proxy . 

The dial is used as
...
	dialer := nc.Opts.Dialer
	nc.conn, err = dialer.Dial("tcp", nc.url.Host)
	if err != nil {
		return err
	}

It called dialer.Dial function.  

http.Transport will use function to do customized
type Transport struct {
...
	Dial func(network, addr string) (net.Conn, error)
...
}

How could I override the Dial.  Is there any suggestions?

**Comment by kozlovic** [comment]
@joyhope Could you share how/why you would be replacing a `net.Dialer` with? As I explained, we cannot simply replace the `Options.Dialer *net.Dialer` with a `CustomDialer` (that would be an interface) because it would break applications that reference `nc.Opts.Dialer` assuming that this is a `*net.Dialer`.
It means that we would need to add yet a new field in `Options` (and setter function) for such custom dialer. This seem a bit excessive at this point.

**Comment by mdevan** [comment]
Not the OP, but have the same request.

Connecting to a NATS server over an SSH tunnel is a use case from my side. Application establishes an SSH connection to a server where gnatsd is running, and has a `*ssh.Client` object that provides the same `Dial(network, address string) (net.Conn, error)` method, but can't be passed to NATS. (And using TLS-based gnatsd connection is not a sufficient replacement for SSH in my case.)

It's only a few lines change within go-nats (but API-breaking changes, I agree), but there is no other way to do this other than fork go-nats.

I do hope there are more users having this use-case than there are users who use `Options.Dialer` assuming it to be a `*net.Dialer` :-)

**Comment by kozlovic** [comment]
> It's only a few lines change within go-nats (but API-breaking changes, I agree), but there is no other way to do this other than forking go-nats.

We cannot break it. The other way is for us to add a new option/setter in order for users to pass a custom dialer and leave the current `Options.Dialer` and `nats.Dialer()` the way they are. We could mark them as "deprecated", but the reality is that we will likely never remove them (or maybe if/when we bump the version to `2.0.0`.
