### ISSUE TITLE
Feature request: add hook to change _INBOX.* topic on Request

### ISSUE THREAD

**Issue by valichek** [nats-io/go-nats#331]
We would like introduce some kind of namespaces for _INBOX.* Some clients should not be able to subscribe on system _INBOX messages like `_INBOX.SYSTEM.*`. It's possible only for old request implementation, but having a hook to replace `_INBOX` with `_INBOX.NAMESPACE` would be very useful.

**Comment by tylertreat** [comment]
Is there a reason you can't prefix the inbox with the namespace? E.g. `NAMESPACE._INBOX.*`.

**Comment by valichek** [comment]
@tylertreat no way check here https://github.com/nats-io/go-nats/blob/master/nats.go#L2048 and here https://github.com/nats-io/go-nats/blob/master/nats.go#L2123-L2130

**Comment by tylertreat** [comment]
I see now. Yes, it is probably reasonable to expose an optional hook for customizing the inbox used in `Request`. Thoughts @kozlovic?

**Comment by kozlovic** [comment]
I am not sure this is necessary. Request() is a convenience method. You are free to use your own reply subject and to a PublishRequest() on it and then do a NextMsg(). In other words, you could easily implement the Request() function to suit your needs.

**Comment by valichek** [comment]
Sure it's possible to re-implement Request just copy-pasting 100% of related code, but again having the hook would be very helpful. I would make PR if accepted

**Comment by ColinSullivan1** [comment]
@valichek ,  Thank you for raising this issue.  As there is a solid workaround (albeit with copy-paste), and we prefer to keep the NATS API small and simple, we're closing this issue for now.  If there is additional interest from the community, we can certainly re-open it.

**Comment by nuhamind2** [comment]
I am interested in this feature, coupled with subject level authorization, a simple _multi tenancy_ can be implemented.

**Comment by derekcollison** [comment]
Multi-tenancy is coming soon in the form of accounts.
