### ISSUE TITLE
CloneTLSConfig does not perform a complete copy in Go 1.8+

### ISSUE THREAD

**Issue by johanbrandhorst** [nats-io/go-nats#335]
Since Go 1.8 `tls.Config` has a field called `GetClientCertificate`. The existing methods for cloning `tls.Configs` in the NATS codebase do not copy this field. Indeed, it should be deferring to  `conf.Clone()` in Go 1.8+ environments.

Related issues:
https://github.com/golang/go/issues/19264
https://github.com/gorilla/websocket/issues/215

**Comment by kozlovic** [comment]
Yes, I added a note in the codebase that this was temporary until a Clone() function was exported. We will need to update go client and gnatsd for Go 1.8+.

**Comment by johanbrandhorst** [comment]
I created a PR for this.
