### ISSUE TITLE
Synchronous Barrier call holds conn mutex

### ISSUE THREAD

**Issue by nussjustin** [nats-io/go-nats#345]
When [`Barrier`](https://godoc.org/github.com/nats-io/go-nats#Conn.Barrier) is called with no active asynchronous subscriptions, the call will be made synchronously with both `nc.mu` and `nc.subsMu` held. Calling any other method on the [`Conn`](https://godoc.org/github.com/nats-io/go-nats#Conn) in the callback will than block the whole connection.

E.g. calling

```go
conn, _ := nats.Connect("nats://127.0.0.1:4222")
conn.Barrier(func() {
	conn.TLSRequired()
})
```

will block since the callback is called synchronously in `Barrier`, which holds the two mutexes.

As long as there is at least one asynchronous subscription, the callback will be called later without any mutex held. So this will work:

```go
conn, _ := nats.Connect("nats://127.0.0.1:4222")
conn.Subscribe("nats_is_awesome", func(_ *nats.Msg) {})
conn.Barrier(func() {
	conn.TLSRequired()
})
```

**Comment by kozlovic** [comment]
@nussjustin Thanks again for an excellent report (and catch!). I had originally started `f` as a go-routine but decided at the last minute that there was no need really. However, you are right, in this case I should have released the locks. The PR #346 addresses that. Thanks!
