### ISSUE TITLE
tag v1.4.0 still reports  nats.Version 1.3.1 

### ISSUE THREAD

**Issue by dvaldivia** [nats-io/go-nats#355]
Release 1.4.0 reports version 1.3.1 on the nats.Version variable

https://github.com/nats-io/go-nats/blob/v1.4.0/nats.go

**Comment by kozlovic** [comment]
Sorry about that. I am adding a test and will make the release process more automated so that it does not happen again. We will probably release a 1.5.0 release soon (maybe tomorrow).

**Comment by kozlovic** [comment]
We released 1.5.0 today (https://github.com/nats-io/go-nats/releases/tag/v1.5.0). We added a test and if we do the release by pushing a new tag (and not directly create it in GH), then that should not happen again.
Thanks!

**Comment by dvaldivia** [comment]
Thanks! Great job!
