### ISSUE TITLE
grpc encoder

### ISSUE THREAD

**Issue by vtolstov** [nats-io/go-nats#396]
As i see nats client have gob and json encoders.Why not create grpc encoder as like gob?

**Comment by derekcollison** [comment]
We have protobuf encoders, is that what you mean?

**Comment by vtolstov** [comment]
yes, i'm not find it in the docs, but after looking at the source and understand how to use it (simple import with _ )

**Comment by derekcollison** [comment]
ok will look at making docs a bit better..

**Comment by gedw99** [comment]
Also need grpc encoder docs or at least a pointer to the original protobufs in GitHub

**Comment by derekcollison** [comment]
For NATS or STAN?

https://github.com/nats-io/go-nats/blob/master/enc_test.go#L173
https://github.com/nats-io/go-nats/blob/master/encoders/protobuf/protobuf_enc.go
