### ISSUE TITLE
After reconnecting, the addresses of 'nc.ConnectedUrl()' and 'nc.Opts.Servers' are different, is this correct?

### ISSUE THREAD

**Issue by guce** [nats-io/go-nats#416]
Connect to NATS
```
	conn, err := nats.Connect(cfg.Addr,
		nats.MaxReconnects(-1), // always reconnect
		nats.DisconnectHandler(disconnectHandler),
		nats.ReconnectHandler(reconnectHandler),
		nats.ClosedHandler(closedHandler))
	if err != nil {
		return nil, err
	}

```

Reconnect event, print both `nc.ConnectedUrl()` and `nc.Opts.Servers`
```
// handle reconnect event
func reconnectHandler(nc *nats.Conn) {
	log.Warn("Reconnect to [%v], config-servers[%v]!", nc.ConnectedUrl(), strings.Join(nc.Opts.Servers, "|"))
}

```

> Reconnect to [nats://172.18.0.1:4222], config-servers[nats://10.4.10.8:4222]!

After reconnecting, the two addresses are different
172.18.0.1 is a gateway address and NATS server address is 10.4.10.8.

Thanks.

**Comment by kozlovic** [comment]
Could you please provide the server configuration? Are you running a standalone server or is it clustered? Do you stop/restart the server to cause the disconnect/reconnect? Thanks!

**Comment by guce** [comment]
The server basically uses the default configuration, cluster mode.
The server has not been manually restarted, but we suspect that it may be disconnected and reconnected due to firewall reasons.

Both the server and the client are running in docker.
The server is running on machine A, using the host network, exposing port 4222.
The client runs on machine B, using the docker default network.
Machine B also runs a NATS-Streaming server, which also uses the host network.

In the event of a problem, the client on machine B is connected to its own gateway address, but this address does not have any NATS service.

We tried to simulate this problem again, but it didn't work.
So ask the community to see if there are any similar issues, or if there is such a possibility from the code.

**Comment by kozlovic** [comment]
Configuration matters. If your server does not specify a specific IP or hostname in the listen specification, the server defaults to `0.0.0.0` which is "any" interface on that machine. When in cluster mode, the server will try to advertise its address for clients in the cluster to be able to (re)connect. Therefore, the server lists all non-local IPs that it can find and send that to both servers in the cluster and clients connecting to it.

When a client gets those URLs, it adds them to the list of URLs that it can use to reconnect. That could be the explanation of what you see.

There are 3 ways to prevent this unexpected URL:
- Be explicit when you define the listen specification `listen: "<machine IP or host>:<port>"
- Use the `no_advertise` config to prevent servers from advertising URLs for clients to connect to. This requires then your clients to be explicitly configured to connect or reconnect to any server in the cluster.
- Use the `client_advertise` config to instruct the server to use that URL when sending to the cluster and clients.

Some information can be found [here](https://github.com/nats-io/gnatsd#clustering). If you read through the "Configuration Options" chapter, there is a reference to advertise addresses.

**Comment by guce** [comment]
Thanks a lot


| |
guce_baresi
邮箱：guce_baresi@163.com
|

Signature is customized by Netease Mail Master

On 12/18/2018 00:18, Ivan Kozlovic wrote:

Configuration matters. If your server does not specify a specific IP or hostname in the listen specification, the server defaults to 0.0.0.0 which is "any" interface on that machine. When in cluster mode, the server will try to advertise its address for clients in the cluster to be able to (re)connect. Therefore, the server lists all non-local IPs that it can find and send that to both servers in the cluster and clients connecting to it.

When a client gets those URLs, it adds them to the list of URLs that it can use to reconnect. That could be the explanation of what you see.

There are 3 ways to prevent this unexpected URL:

Be explicit when you define the listen specification `listen: ":"
Use the no_advertise config to prevent servers from advertising URLs for clients to connect to. This requires then your clients to be explicitly configured to connect or reconnect to any server in the cluster.
Use the client_advertise config to instruct the server to use that URL when sending to the cluster and clients.

Some information can be found here. If you read through the "Configuration Options" chapter, there is a reference to advertise addresses.

**Comment by guce** [comment]
But there is still a question, if my two NATS-Streaming servers belong to different clusters, will this problem not occur?

**Comment by kozlovic** [comment]
@guce Not sure I understand your question. Could you please elaborate?

**Comment by guce** [comment]
> When in cluster mode, the server will try to advertise its address for clients in the cluster to be able to (re)connect.

What I want to make clear is, the advertise function mentioned above should be limited to the inside of a cluster? Even if the server listen `0.0.0.0`, the client will not connect to the server of another cluster.

For example:
There is a 3 nodes NATS cluster and a NATS-Streaming server, and the servers of the NATS cluster are listening at `0.0.0.0`.
If there is such a possibility, the address of the NATS cluster advertisement to the client just happens to allow the client to connect to the NATS-Stream server when reconnection occurs?

**Comment by kozlovic** [comment]
I think you are still confused about the relation between NATS Streaming Server and NATS Server. I would recommend that you look at https://github.com/nats-io/nats-streaming-server#concepts.

The NATS cluster will form a full mesh in which clients connected to it can communicate. The Steaming Server acts as a client and define a Streaming cluster name, which is used internally in the subject space between the streaming server and its clients to isolate communication.

**Comment by kozlovic** [comment]
@guce Is this still an issue or can we close? Thanks!

**Comment by guce** [comment]
@kozlovic 

Sorry for replying so late. 
We can't reproduce this problem now. You can close this issue first.

Thanks!
