### ISSUE TITLE
How to prevent a Subscriber on same connection as publisher from receiving a message?

### ISSUE THREAD

**Issue by UltraNemesis** [nats-io/go-nats#424]
As the title says, if I have 5 instances of a service each opening a connection to nats and there is subscriber setup for a topic on each. Now when I publish to the topic from one of these nodes, I don't want the node from which it was published to get the message. i.e. nats connection on which the publish was done should not receive the message. 

Any way to achieve this?

**Comment by ripienaar** [comment]
Try passing the `NoEcho()` option.

**Comment by kozlovic** [comment]
That's right. You can pass the `NoEcho()` option like that:
```
nc, err := Connect(url, NoEcho())
if err != nil {
 ...
}
```
Note that you must connect to a NATS Server `1.2.0` and above to be able to use this feature.
