### ISSUE TITLE
Why flushChanSize is 1024?

### ISSUE THREAD

**Issue by MaruHyl** [nats-io/go-nats#436]
I think value 1 is better

**Comment by derekcollison** [comment]
When fast producers are running we do not want them blocked trying to kick the flusher go routine, that is why it is buffered.

You can try on your own the publisher benchmarks with and without that change and see the difference, especially if multiple go routines publishing data.

**Comment by MaruHyl** [comment]
@derekcollison  Sorry for reopen it.
But I mean ` feh:=make(chan struct{},1)` is better here.
1.It save some memory than 1024 and will never be blocked too.
```
select {
	case nc.fch <- struct{}{}:
	default:
}
```
2.And `flusher`will not wake up many times when `bw` is already empty
```
for {
        // if buffer is 1024, it will awake many times here 
        // even though `bw` is already flush before.
	if _, ok := <-fch; !ok {
	    return
       }
       ....
}
```

**Comment by derekcollison** [comment]
You may have a point using the non blocking code on the channel.

**Comment by derekcollison** [comment]
Want to send a PR?

**Comment by derekcollison** [comment]
If not no worries I can take a look today. Thanks again for the persistence, you are right here.

**Comment by MaruHyl** [comment]
@derekcollison Let me give it a try. I will send a PR later :)

**Comment by derekcollison** [comment]
ok thanks. Appreciate the contribution!
