### ISSUE TITLE
When use QueueSub, is there only one subscriber can receive the message in any case?

### ISSUE THREAD

**Issue by guce** [nats-io/go-nats#439]
If the message sent to the selected subscriber fails, will it be sent to another subscriber in the queue group? Or will drop the message in this case.

**Comment by ripienaar** [comment]
Depends how you mean fail I guess - in general gnatsd will put it in the TCP buffer of the receiver chosen at random and that is all, there is no concept of acks etc.  For that you need to use NATS Streaming.

**Comment by guce** [comment]
For my case, I can handle message loss, but if two subscribers receive the same message, there will be a bigger problem.

**Comment by ripienaar** [comment]
gnatsd is at-most-once, so a message will rather be lost than redelivered

**Comment by guce** [comment]
thanks
:)

**Comment by wallyqs** [comment]
thanks @ripienaar :) as mentioned the NATS server will not redeliver the message once it has been delivered, so it will not be processed twice by different subscribers.
