### ISSUE TITLE
on Publish nats: Connection Closed handling

### ISSUE THREAD

**Issue by NaerChang2** [nats-io/go-nats#448]
nats server is 1.0.6
nats go client is 1.0.5 (I know it's old)

So far we didn't observe any issues but yesterday in a new env (still same server/client version) we noticed Publish() was not working (i.e.: NATs server not receiving anything). After adding some logging we saw ErrConnectionClosed (i.e.: "nats: Connection Closed handling").

I couldn't find meaningful information about how we should handle this in this library. In the streaming client lib I saw a post about this case but they recommend reconnecting but I am not sure if it applies to this lib (https://github.com/nats-io/csharp-nats-streaming/issues/63).

Questions:

1) I know internally it already does reconnect so what could be the reason of ErrConnectionClosed (server was running at the time no errors showing running as a docker container)? I assume it tried the default number of reconnect but still failed.

2) What is the recommended handling logic? If you have an example it would be great. I see that in newer version (1.7.2) of the client lib there is one callback for disconnected. Basically some best practice guidance regarding how we should handle connection error with this client lib would be appreciated (especially during lifetime of the connection while doing Publish() and things like that).

**Comment by derekcollison** [comment]
https://github.com/nats-io/go-nats/blob/master/examples/nats-sub/main.go#L86

**Comment by NaerChang2** [comment]
Just for clarification are you saying there is nothing we can do other than configuring connection options for handling connection errors (particularly ErrConnectionClosed)? I just want to be clear so we can document how we arrived to our final implementation for this issue.

Thanks

**Comment by kozlovic** [comment]
@NaerChang2 The library automatically tries to reconnect, but by default has a limited number of attempts (and delay). Registering the callback is just to let you know when the connection is permanently lost. In that case, you would need to recreate the connection and its subscriptions.
If the library is able to reconnect on its own, then the subscriptions will be automatically resent to the server and any published messages that happened during the reconnect and that fit in the reconnect buffer will be flushed.
But as you know, your library is quite old so you may want to plan an upgrade.

**Comment by NaerChang2** [comment]
Awesome. This is the information I was hoping to get. I now have enough details to implement a proper handling.

Thanks 👍

**Comment by VishwasSomasekhariah** [comment]
@NaerChang2 We are facing a similar issue, Could you please share your experience on how you fixed it?

**Comment by mihailozarinschi** [comment]
Got into similar issue with `nats:2.10.1-alpine` and client version `v1.28.0`.  

Client configured with MaxReconnects=-1 (must never stop trying).

@NaerChang2 @VishwasSomasekhariah Did you fix it somehow?

**Comment by VishwasSomasekhariah** [comment]
@mihailozarinschi Unfortunately I did not find the root cause of the problem. I changed the deployment file to add a debug env variable, and that redeployed the NATS server and my issue was resolved.

**Comment by bonnis** [comment]
@mihailozarinschi We also encountered a similar issue using `nats:2.10.0-alpine` Did you manage to resolve it?

@VishwasSomasekhariah What is this debug env variable and how do you add it, if I may ask?

**Comment by VishwasSomasekhariah** [comment]
@bonnis Sorry for the delayed response! 
I hope you were able to figure out the what debug env variable is and how to add it. If not [here](https://docs.nats.io/running-a-nats-service/configuration#monitoring-and-tracing:~:text=debug,false%2C%20disabled) is a link to learn about it. If you check your deployment file for the NATS server, by default this variable is missing from the file. So, you would have to add it and set the value to `true` to be able to see more debug log messages, which hopefully helps you understand the root cause of your problem.

**Comment by bonnis** [comment]
@VishwasSomasekhariah A thousand thanks for the helpful response! 🙌
