### ISSUE TITLE
unable to run the nats-pub/sub go program

### ISSUE THREAD

**Issue by zackws** [nats-io/go-nats#450]
trying to run the examples nats-pub and nats-sub, had this error 

nats-pub.go:20:3: found packages bench (main.go) and main (nats-pub.go) in C:\go-work\src\github.com\nats-io\go-nats

please help me, i think it has something to do with the GOPATH.

**Comment by wallyqs** [comment]
Might be easier to `go get` the examples, you could try: 

```sh
cd $GOPATH
go get github.com/nats-io/go-nats/examples/nats-pub
go get github.com/nats-io/go-nats/examples/nats-sub
$GOPATH/bin/nats-pub
$GOPATH/bin/nats-sub
```

**Comment by zackws** [comment]
I'm working on windows and i got this error when i tried to use go get:
package github.com/nats-io/go-nats/examples/nats-pub: cannot download, C:\go-work is a GOROOT, not a GOPATH. For more details see: 'go help gopath'

PS: GOROOT is in C:/Go not in C:/go-work

**Comment by zackws** [comment]
Changed the path i got another error:
C:\tools\Go projects>go get github.com/nats-io/nats-top
# cd .; git clone https://github.com/nats-io/nats-top C:\tools\Go projects\src\github.com\nats-io\nats-top
Cloning into 'C:\tools\Go projects\src\github.com\nats-io\nats-top'...
fatal: Invalid path '/cygdrive/c/tools/Go projects/C:\tools\Go projects\src\github.com\nats-io\nats-top': No such file or directory
package github.com/nats-io/nats-top: exit status 128

**Comment by wallyqs** [comment]
Looks like you are using cygwin? Maybe you might be running into this issue? => https://github.com/golang/go/issues/23155#issuecomment-355558176
