### ISSUE TITLE
Callback not getting called when using encoded connection

### ISSUE THREAD

**Issue by dvaldivia** [nats-io/go-nats#453]
Hi,

I have a problem with a `QueueSubscribe` that is not triggering the callback for published events from another pod on kubernetes. This works totally fine on my local, but deployed on k8s is not working.

The strange thing is that this used to work on a different service that was replaced, the publishing service is the same but the subscribing service was replaced with a new one.

Upon investigatin on `/connz` I found that the `deaf` QueueSubscriber is receiving the bulk events

*Initial state*
```
{
      "cid": 10,
      "ip": "10.8.0.38",
      "port": 39240,
      "start": "2019-04-10T05:11:29.299050658Z",
      "last_activity": "2019-04-10T05:11:29.301004541Z",
      "uptime": "3s",
      "idle": "3s",
      "pending_bytes": 0,
      "in_msgs": 0,
      "out_msgs": 0,
      "in_bytes": 0,
      "out_bytes": 0,
      "subscriptions": 2,
      "lang": "go",
      "version": "1.7.2"
    }
``` 

*Upon starting my kubernetes job that publishes many events*

```
{
      "cid": 10,
      "ip": "10.8.0.38",
      "port": 39240,
      "start": "2019-04-10T05:11:29.299050658Z",
      "last_activity": "2019-04-10T05:22:26.292019018Z",
      "rtt": "495µs",
      "uptime": "11m0s",
      "idle": "3s",
      "pending_bytes": 0,
      "in_msgs": 0,
      "out_msgs": 473,
      "in_bytes": 0,
      "out_bytes": 57549,
      "subscriptions": 2,
      "lang": "go",
      "version": "1.7.2"
    }
```

The way the subscription is started

```
_, err := natsCnx.QueueSubscribe("new_post", "job_workers", indexNewPost)
```
I tried changing the queue name.

After this activity, the callbacks for the 2 subscriptions on this service were never invoked.

My question is how to debug this? the subscriber seems to be received all the messages properly, so I doubt it's `gnats`, it's just that the callbacks are not happening.

**Comment by wallyqs** [comment]
Is there enough logging on the `indexNewPost` function to trace when the message is received? Is this a bare connection or a connection using an encoder?
It could as well to use an async error callback handler, in case of the encoded connection the errors on umarshalling could be logged there https://github.com/nats-io/go-nats/blob/3c1cfc569bbd2b9974a8bfd7ef4a3aa5c0739bb1/nats.go#L893-L901

**Comment by dvaldivia** [comment]
Yes, the `indexNewPost` function has a `log.Println` on it's first line
It's an encoded connection

If other services publish to the `new_post` subject, the events are received just fine, so I've double checked that the encoded objects are the same in all possible ways, then again, this works totally fine on local, but somehow inside a container on kubernetes is not behaving the same.

Using the error callback on the error connection i get the following error

```
2019/04/11 02:15:42 ERROR UNMARSHALLING nats: Got an error trying to unmarshal: illegal base64 data at input byte 8
```
It's exactly the error for for `QueueSubscribe` coming from different sources with different structs. 

I tried verifying the struct being sent was fine, I even serialized it before passing it to `Publish` everything seems in order, other services who publish to this subject do get picked up

The structure being sent is not too strange. ie:

```
type newPost struct {
	UserId      []byte
	PostId      []byte
	Description string
	DateAdded   time.Time
}
```

Then again, running this code locally everything seems fine, but it's only in k8s that it's not working, I find it strange that both situations are byte 8 related error

Any other idea?

**Comment by wallyqs** [comment]
🤔well at least looks like the issue is around the serializing/deserializing logic... which encoder is being used? (json, protobuf, ...) The not working on Kubernetes part but ok locally sounds like there might be a difference between the dependencies in both environments somehow, are both the same Go version / server etc...?

**Comment by dvaldivia** [comment]
The encoder is nats.JSON

All the containers get built the same, first `from golang` then `from scratch` and the dependencies are vendored

I ran the following experiment on my local, pulled the same docker image used in k8s, started the conflicting service (the subscriber) and started the publisher in a container as well, it worked just fine 😞my local has docker desktop for mac 2.0.0.3

**Comment by dvaldivia** [comment]
the new service that's having the problem replaced another service that didn't had the issue, the only difference between this two services is that the previous one was a `Deployment` and the new service is a `StatefulSet`, I really don't think that should cause a problem

I tried the other 2 encoders

GOB
```
2019/04/12 15:38:17 ERROR UNMARSHALLING nats: Got an error trying to unmarshal: gob: bad data: undefined type CommonType = struct { Name string; Id int; }
```
here I don't know what is it talking about, I'm not sending a CommonType struct

DEFAULT
```
2019/04/12 15:41:00 ERROR UNMARSHALLING nats: Got an error trying to unmarshal: nats: Default Encoder can't decode to type main.newPost
```

**Comment by kozlovic** [comment]
```
2019/04/12 15:38:17 ERROR UNMARSHALLING nats: Got an error trying to unmarshal: gob: bad data: undefined type CommonType = struct { Name string; Id int; }
```
Well, that may be the crux of the issue. You may be getting messages from sources that you are not expecting in this new deployment. Maybe you are listening to wrong subject, or new producers are sending messages of non-expected content type to the subject your subscription is listening to?

**Comment by dvaldivia** [comment]
@kozlovic I don't think so, this code runs just fine locally and inside docker on local, so locally I can verify I'm listening to the right subject and the producer is sending the right message.

Strangely enough, other producers of the same topic do get picked up by this subscriber, these producers run the same version of nats/go and are indeed the same container, but instead of spamming multiple publish events, they only publish 1 event every now and then

**Comment by dvaldivia** [comment]
also I have two producers with two different structs on two different subjects, the error is the same on the subscriber who listens to both subjects

`new_post` and `new_user` and published by different containers inside k8s, different structs, it's rare that both fail on byte 8

```
2019/04/12 16:09:27 ERROR UNMARSHALLING new_post error: nats: Got an error trying to unmarshal: illegal base64 data at input byte 8
2019/04/12 16:09:27 ERROR UNMARSHALLING new_user error: nats: Got an error trying to unmarshal: illegal base64 data at input byte 8
```

**Comment by dvaldivia** [comment]
Is there a way to get the client to output what was received over the wire?

**Comment by kozlovic** [comment]
I would run another non encoded connection with subscription to receive bare bytes and can dump those to try see what's wrong.

**Comment by dvaldivia** [comment]
If the publishing happen sporadically it works well (6 minutes difference, non batched publish)
```
2019/04/12 16:20:06 ERROR UNMARSHALLING new_post error: nats: Got an error trying to unmarshal: illegal base64 data at input byte 8
2019/04/12 16:26:13 Index new post
2019/04/12 16:26:13 ad026572-5d3f-11e9-815c-0a580a08000f
```

I added the non-encoded connection subscription (this is not using `QueueSubcribe`) and I can see the message
*non-encoded vs encoded queue vs non-encoded queue*
```
2019/04/12 16:35:46 NON ENCODED MESSAGE
2019/04/12 16:35:46 {"UserId":"154a71c6-39db-46af-9079-3e924fe9e5c7","PostId":"e1735c96-124f-11e9-8da5-0a580a0800e8","Description":""}
2019/04/12 16:35:46 ERROR UNMARSHALLING new_post error: nats: Got an error trying to unmarshal: illegal base64 data at input byte 8
2019/04/12 16:40:08 NON ENCODED MESSAGE QUEUE
2019/04/12 16:40:08 {"UserId":"32568309-5c62-4cfb-b589-61fb2ad52180","PostId":"448e3234-144a-11e9-9985-0a580a08000e","Description":"taco time ! 🌮 "}
```
this shines some light I guess, the non-encoded connection is working totally fine, even if it's a `QueueSubcribe`, only the encoded connection `QueueSubcribe` is not working properly in this k8s environment.

I could switch this this connection, what are the disadvantages? Still I use QueuedSubscriptions everywhere else

**Comment by wallyqs** [comment]
Not using the encoded connection is fine since it is just a helper, would give you more control in this in debugging without having to use an async callback for example. About the unmarshalling issue, from the snippet you posted we can see the problem is in the type struct: 

These fields are being represented as a string in the JSON payload:
```
{"UserId":"32568309-5c62-4cfb-b589-61fb2ad52180", "PostId":"448e3234-144a-11e9-9985-0a580a08000e"...
```

But in the type struct that you mentioned, they are represented as `[]byte`s:

```go
type newPost struct {
	UserId      []byte
	PostId      []byte
...
```

so serializing/deserializing would fail since the Go JSON library would try to treat the string as a base64 encoded byte field as part of the JSON payload, something like this for example:

```go
{"UserId":"MzI1NjgzMDktNWM2Mi00Y2ZiLWI1ODktNjFmYjJhZDUyMTgw"...
```

If on the subscriber side you change the type to use strings it seems like this would work.

**Comment by dvaldivia** [comment]
that's a nice catch, my question here would be, How did it know it's a UUID if I clearly stored []byte in the struct? 

I'm not passing any UUID else I wouldn't be able to compile my code, so how is it coming up with the UUID value on deserialization?

*my publish code*
```
err := natsCnx.Publish("new_post", &newPost{
                                UserId:      post_user_id.Bytes(),
                                PostId:      postid.Bytes(),
                                Description: description,
                        })
```

`post_user_id` its a `gocql.UUID` type of variable, so I'm get the `Bytes()` to I can construct my struct to publish on nats

More over it wouldn't explain why this only happens on k8s, not on docker-compose or local

**Comment by dvaldivia** [comment]
I'm seeing that the encoded connection just marshals the `interface{}` it receives to json, so maybe the json marshaling is picking up the bytes as UUID.

I see now it's more efficient to use a traditional connection, I could simply pass the bytes of my struct right? 

Maybe I should try marshaling a protobuf and publishing that instead, might be a more efficient way since less bytes would travel the wire in that format than in string (json) format, al thought that's solving the problem in a different way, but I can understand why my bytes get lost using an encoded connection

**Comment by wallyqs** [comment]
What type is gocql.UUID? byte or string? The code compiles but due to using different types the encoding is failing, I would try to find out where in the stack the incompatibility is arising, is the type reused by both publishers and consumer? If you cannot find the root cause, you could first deserialize using the type with strings then if on unmarshal error use the one with bytes with the non encoded connection format.

**Comment by wallyqs** [comment]
Right using protobuf in this case could help avoiding the impedance mismatch since can rely on the protobuf schema.  Non encoded connection generally more efficient too since not using reflect.

**Comment by dvaldivia** [comment]
I replaced all the encoded connections across all my services and passed messages using protocol buffers, the problem is resolved.

Thanks for your time and effort.
