### ISSUE TITLE
Conn.Subscribe asynchronous?

### ISSUE THREAD

**Issue by JensRantil** [nats-io/go-nats#458]
I just put together [a tiny application which continuously runs end-to-end tests against NATS](https://gist.github.com/JensRantil/56cc0d36d71d94aea57789bc2260013c/7e4b1448cff1d999ddc2276f05763a678906304e). My NATS cluster is behind a single DNS record, so the test continously reconnects to NATS to make sure I'm testing connectivity between the NATS servers.

The problem is that I'm seeing timeouts around 25% of the calls when running it against a local `gnatsd` instance. I've put a [workaround](https://gist.github.com/JensRantil/56cc0d36d71d94aea57789bc2260013c/7e4b1448cff1d999ddc2276f05763a678906304e#file-nats-checker-go) in place on line 218. The issue seems to be that https://godoc.org/github.com/nats-io/go-nats#Conn.Subscribe is registering asynchronously to NATS. How to recreate:

```bash
$ gnatsd &
$ go build . && ./nats-checker &
$ sleep 30
$ curl localhost:8080/metrics
$ # notice natscheck_test_timeout is larger than 0
```

I also tested using https://godoc.org/github.com/nats-io/go-nats#Conn.SubscribeSync (see revision 2 [here](https://gist.github.com/JensRantil/56cc0d36d71d94aea57789bc2260013c)), but in that case I'm receiving timeout all the time so I guess it doesn't work for some reason. (I also tried adding a `time.Sleep(...)` after the https://godoc.org/github.com/nats-io/go-nats#Conn.SubscribeSync call.

Is https://godoc.org/github.com/nats-io/go-nats#Conn.Subscribe expected to be async? If so, I think the behaviour should be documented. Or is this considered a bug?

**Comment by wallyqs** [comment]
have you tried using Flush? That API can help ensure that a subscription is ready before sending the message and avoid having to use Sleep

**Comment by JensRantil** [comment]
Ah, finally figured out I need to call `nc.Flush()` to make sure that that the subscription landed on the server... https://gist.github.com/JensRantil/56cc0d36d71d94aea57789bc2260013c#file-nats-checker-go now works. 🎉 

Would it make sense to document that connection might need to be flushed to make sure that the subscription is actually in place on the server? If totally fine with not doing it and closing this issue without, though.

**Comment by JensRantil** [comment]
Another follow-up question, I tried calling `nc.Flush()` after `nc.SubscribeSync(...)` in https://gist.github.com/JensRantil/56cc0d36d71d94aea57789bc2260013c/9a36b8d0d4c38701de1317a0a82ff6efc5bb1a86 and I'm only seeing timeouts in that case. Should I expect that to work?

**Comment by wallyqs** [comment]
Thanks for the feedback @JensRantil this is certainly a FAQ so we could add some more docs around it, there is a mention about Flush [here](https://nats.io/documentation/writing_applications/publishing/) for the case of publishing but maybe should note something similar for subscribe or a section around synchronizing multiple connections probably.

re: subscribe sync, it should work the same but might be tricky to synchronize among multiple connections as you have in the gist right now, have you considered using Request instead for this? Maybe something like: 

```go
package main

import (
	"fmt"
	"log"
	"time"

	"github.com/nats-io/go-nats"
	"github.com/nats-io/nuid"
)

func main() {
	ncA, err := nats.Connect("demo.nats.io")
	if err != nil {
		log.Fatal(err)
	}

	ncB, err := nats.Connect("demo.nats.io")
	if err != nil {
		log.Fatal(err)
	}

	// Generate unique subject and sub for this test.
	inbox := fmt.Sprintf("natscheck.%s", nuid.Next())
	_, err = ncA.Subscribe(inbox, func(m *nats.Msg) {
		ncA.Publish(m.Reply, []byte("OK"))
	})
	if err != nil {
		log.Fatal(err)
	}

	// Ensure subscription is ready in the server my making a roundtrip.
	ncA.Flush()

	// Send requests and wait for single response.
	startAt := time.Now()
	timeout := 5 * time.Second
	_, err = ncB.Request(inbox, []byte(""), timeout)
	if err != nil {
		log.Fatal(err)
	}
	log.Println("Latency:", time.Since(startAt))
}
```

Btw, in case it would help there is a latency framework for NATS here as well https://github.com/nats-io/latency-tests/blob/master/latency.go

**Comment by JensRantil** [comment]
> re: subscribe sync, it should work the same but might be tricky to synchronize among multiple connections as you have in the gist right now

🤔 Every test run I have, I'm working on a unique topic/subject, so I'm having a hard time to understand why this doesn't work. Shouldn't a `conn.SubscripeSync(...);conn.Flush()` send off a subscription to the server?

> have you considered using Request instead for this?

Yes, considered it. I'm sure it would work. I guess it's a bit of a pet pieve, but my use-case is one-way latency so I'd prefer to test for that.

**Comment by kozlovic** [comment]
@JensRantil For the SubscribeSync test, should you not let go the sender (started.Done()) before calling sub.NextMsg()?

**Comment by JensRantil** [comment]
@kozlovic No, if I do the message will be sent to the void as the topic will not have been created.

**Comment by kozlovic** [comment]
What I meant is that in https://gist.github.com/JensRantil/56cc0d36d71d94aea57789bc2260013c/9a36b8d0d4c38701de1317a0a82ff6efc5bb1a86, line 208 you have flushed and made sure that subscription is registered. But then line 218 you call NextMsg() but notify the sender that you are ready only at line 233. So in a case where you have 1 sub, 1 sender, then the first NextMsg() will timeout.

**Comment by kozlovic** [comment]
You don't need to be in NextMsg() to not lose the message. If the subscription is created, interest is registered in the server. When message is published, server sends to client library that will queue that message for the NextMsg() call. Like for async subs, there are limits for this queuing that is driven by Sub.SetLimits()

**Comment by JensRantil** [comment]
Ah, that explains it! Thanks! I'll close this issue. Feel free to improve documentation if you want.
